SYNC_VERSION = "v0.1"
INGEST_VERSION = "v0.1"
CHESSCOM_ENDPOINT_GAMES = "games"
COACH_PROMPT_VERSION = "v0.1"
COACH_SCHEMA_VERSION = "v0.1"
MOVE_COACH_PROMPT_VERSION = "v0.4"
MOVE_COACH_SCHEMA_VERSION = "v0.2"
COMMENTARY_WIZARD_PROMPT_VERSION = "v0.1"
COMMENTARY_WIZARD_SCHEMA_VERSION = "v0.1"
GAME_RECAP_PROMPT_VERSION = "v0.1"
GAME_RECAP_SCHEMA_VERSION = "v0.1"
INSIGHTS_COACH_PROMPT_VERSION = "v0.1"
INSIGHTS_COACH_SCHEMA_VERSION = "v0.1"

# Deep Insights - Elite Level Analysis
DEEP_INSIGHTS_PROMPT_VERSION = "v1.0"
DEEP_INSIGHTS_SCHEMA_VERSION = "v1.0"
OPENING_INSIGHTS_PROMPT_VERSION = "v1.0"
OPENING_INSIGHTS_SCHEMA_VERSION = "v1.0"
TIME_INSIGHTS_PROMPT_VERSION = "v1.0"
TIME_INSIGHTS_SCHEMA_VERSION = "v1.0"

# Limits for API cost control
DEFAULT_DEEP_INSIGHTS_GAMES = 10
MAX_DEEP_INSIGHTS_GAMES = 25
